### ISSUE TITLE
Not caching after add a product to cart

### ISSUE THREAD

**Issue by arisdario** [PHOENIX-MEDIA/Magento-PageCache-powered-by-Varnish#13]
I have noticed via support ticket the issue but i see that was ignored, the issue with this module is that when you add a product to the basket, Varnish just break and MISS every hit, tested on http://magento.phoenix-media.eu/
1. Navigate all pages, to get the first hit.
2. Add a product to cart, Checkout or just Delete it from cart.
3. Navigate again the pages you've navigated before, and see if are still fast.

On firebug you will see that X-Cache will return MISS, to cache again you need to remove the cookies from the entire site, and voila it will cache again.

But... you need to tell this to each client visit your webiste... 
So, for some people that just navigate your website and not add a product to cart is good, but for possible buyers the varnish module is not good, also on add a product to cart it show empty cart !.

Hope the team resolve this issue !

**Comment by epiblue** [comment]
LOL!!!!!! SPENT DAYS CONFIGURING IT TO FIND THAT IT'S BASICALLY USELESS !!!

**Comment by arisdario** [comment]
It is easy, but you need some minimum knowledge about installing apps on Centos or Ubuntu Server, after installing Varnish you just need to reverse the 80 port between Apache or Nginx and Varnish to get Varnish working on front, then just copy and adjust as your requeriments the vcl file.

What i have asked and sugested here is/"Was" a bug in the plugin, they has fixed the bug but only on Paid version, for the free version the bug is still there.

Keep in mind that there are some other bugs, like adding product to cart, some times it will not add your product to the cart and will show Cart empty, the fixed this with the keys but is not enough, search a bit more on google and you will find a custom module created to fix this issue.

Best regards,
