### ISSUE TITLE
Checkout Form Key Issue

### ISSUE THREAD

**Issue by robsonlopes** [PHOENIX-MEDIA/Magento-PageCache-powered-by-Varnish#17]
I have strange problem at checkout and in the client area, see the screenshot
http://screencast.com/t/pgbth6ez4jF

<input name="form_key" type="hidden" value="<esi:include src=" http:="" virtualfashion.com.br="" varnishcache="" getformkey="" "="">

**Comment by ihor-sviziev** [comment]
@johnjyin I see that now you fixed this issue. Looks like you added "-p esi_syntax=0x03" to startup parameters.

**Comment by hugodiasneto** [comment]
Same problem here :(

**Comment by ihor-sviziev** [comment]
@hugodiasneto you have same issue like me or like guy from first post? If same like me - try add "-p esi_syntax=0x03" to startup parameters

**Comment by matthiaskomarek** [comment]
@ihor-sviziev i got the same problem. do you have solved this issue?

**Comment by ihor-sviziev** [comment]
@matthiaskomarek no, now we using older version of this module and implemented hack for skipping form key validation, but it can be unsecure.

**Comment by KevinMace** [comment]
I have the same issue with the ESI include tag displaying on the frontend. I ended up doing the same as @ihor-sviziev by using the older version which does not use ESI, then added a 'hack' to remove form key validation.

**Comment by Cranke** [comment]
This is due to bad quoting.

change lines 24 and 25 of app/code/community/Phoenix/VarnishCache/Helper/Esi.php 

from

    const ESI_INCLUDE_OPEN  = '<esi:include src="';
    const ESI_INCLUDE_CLOSE = '" />';

to

    const ESI_INCLUDE_OPEN  = "<esi:include src='";
    const ESI_INCLUDE_CLOSE = "' />";

**Comment by chougron** [comment]
I fixed this by adding "-p esi_syntax=0x03" to my startup parameters (as said in the README) then, editing the given .vcl file as accordingly :

Search for “sub vcl_fetch {“ And add just below :
    set beresp.do_esi = true;

Then I restarted varnish service, flushed varnish cache in Magento settings, cleaned the cookies.

**Comment by ihor-sviziev** [comment]
@Cranke or @chougron could you create pull request which will fix those issue?

**Comment by Cranke** [comment]
how can i do that without forking the whole project?

**Comment by ihor-sviziev** [comment]
@PHOENIX-MEDIA could you merge those changes?

**Comment by Jonathonbyrd** [comment]
@Cranke I've confirmed that this was the issue with my install @ http://residualdrivers.com Thanks for that fix!

**Comment by djgoulaer** [comment]
@Cranke 
Hello friends!
I was very pleased to see everyone's efforts to solve this annoying problem.

The solution mentioned above was excellent, but not fully resolved the issue.
As you can see from the images below, an error occurred in the javascript code that creates the cockie PAGECACHE_FORMKEY.

I auditioned on a clean installation of Magento 1.9.1.1

![capturar](https://cloud.githubusercontent.com/assets/3249296/7665233/fb2aeff6-fb84-11e4-8c5a-094068694644.PNG)
![capturar1](https://cloud.githubusercontent.com/assets/3249296/7665234/fb2c61b0-fb84-11e4-8d7c-d17d068fb325.PNG)

**Comment by Cranke** [comment]
ok we can change that, too.
in app/design/frontend/base/default/template/varnishcache/cookie/formkey.phtml
change line 36 from

    '<?php echo $_formKeyValue; ?>',

to 

     "<?php echo $_formKeyValue; ?>"

clear caches and the code will work.

**Comment by djgoulaer** [comment]
@Cranke Thank you!
