### ISSUE TITLE
Retreiving formkeys via esi

### ISSUE THREAD

**Issue by domeglic** [PHOENIX-MEDIA/Magento-PageCache-powered-by-Varnish#29]
I am confused about how the form key integration via esi works. The formkeys are replaced with the esi tag that has a URL: "magento/varnishcache/getformkey". 
But I don't see any controller that would have this action, so how is it supposed to work? Am I missing some configuration?

**Comment by pocallaghan** [comment]
I was confused about the same thing originally. Upon investigation, if you look through the provided vcl files, they intercept requests for that route, and generate a random formkey in Varnish itself. This is obviously going to be more efficient than going back to the webserver.

**Comment by domeglic** [comment]
I see, thanks for the answer.
