### ISSUE TITLE
Admin Port and Admin Secret not in configuration page

### ISSUE THREAD

**Issue by codesse** [PHOENIX-MEDIA/Magento-PageCache-powered-by-Varnish#40]
Hello,

although README.md informs to configure Admin Port and Admin Secret, those fields are not present in the phoenix-media pagecache configuration page.
They are neither present in core_config_data table or grepping the downloaded code.
Is there another way to inform the plugin about admin port and admin secret?
If you press the purge varnish cache button at the cache configuration page it says it's ok, but how has it spoken to varnish without knowing both admin port and admin secret?

Thanks

**Comment by codesse** [comment]
Hello,

I see in the .vcl there is a 'purge' command associated to a vcl. 
So it is the README.md that needs a 'patch', maybe.

Thanks,

**Comment by PHOENIX-MEDIA** [comment]
These configs have been removed from code as they've never been used. Please ignore the readme here.
