### ISSUE TITLE
Fatal error: Call to a member function generateDesignExceptionSub()

### ISSUE THREAD

**Issue by joridos** [PHOENIX-MEDIA/Magento-PageCache-powered-by-Varnish#41]
Hey folks, I've been updated the module to the version 4.2.3, but when I save the configuration in the admin:

Fatal error: Call to a member function generateDesignExceptionSub() on a non-object in /att/arclube/app/code/community/Phoenix/VarnishCache/Model/Observer.php on line 325

Any Idea?

the code is:

```php
            $designExceptionSubSnippet = Mage::getSingleton('varnishcache/vcl')
                ->generateDesignExceptionSub();
```

But I not found the Model! o.0

**Comment by rob3000** [comment]
This relates to [issue 37]( https://github.com/PHOENIX-MEDIA/Magento-PageCache-powered-by-Varnish/issues/37) where there is no model.
