### ISSUE TITLE
Getting "undefined symbol: MD5" when using new default_4.1.vcl

### ISSUE THREAD

**Issue by timkley** [PHOENIX-MEDIA/Magento-PageCache-powered-by-Varnish#43]
```
Message from dlopen:
Compiled VCL program failed to load:
  ./vcl._thEzyRX.so: undefined symbol: MD5
Running dlopen failed, exited with 1

VCL compilation failed
```

What can I do to fix this issue? My current Varnish version is 4.0.3 but it looks to me as if this is no issue of Varnish itself.

**Comment by niels-phoenix** [comment]
You need to have V4.1 and the openssl-devel package installed

**Comment by SiddiqueAhmad** [comment]
i have v4.1 and installed the openssl-devel but still 

Starting Varnish Cache: Error:
Message from dlopen:
Could not load compiled VCL.
        dlopen(vcl_boot/vgc.so) = vcl_boot/vgc.so: undefined symbol: MD5
Running dlopen failed, exited with 1
VCL compilation failed

**Comment by SiddiqueAhmad** [comment]
it was mulitline issue, i put all on same line and it worked

**Comment by xtremevision** [comment]
Hi, what did you put all on the same line more precisely? Can you share the final vcl please?
Cheers,
Michael.

**Comment by PHOENIX-MEDIA** [comment]
You need to reference the openssl library in the Varnish startup parameters. Read section "3.2 Libraries needed" here https://github.com/PHOENIX-MEDIA/Magento-PageCache-powered-by-Varnish #rtfm

**Comment by eharvest** [comment]
Got the same error when I replace the default.vcl with Phoenix Magento Cache's one.

Should I just append `-p 'cc_command=exec cc -fpic -shared -Wl,-x -o %o %s -lcrypto -lssl'` to the end of `ExecStart=` in /etc/systemd/system/varnish.service? It doesn't look right as I get InvalidArgument error.

Also when I manually start varnishd with: `varnishd -a :80 -f /etc/varnish/default.vcl -s malloc,100M -p 'cc_command=exec cc -fpic -shared -Wl,-x -o %o %s -lcrypto -lssl'`, then check my varnish status, it's not refreshing and still shows _Active: failed_

Someone also mentioned editing /etc/default/varnish doesn't work anymore. So is varnish.service the only file where you can add startup parameters?

I followed the instructions for both Varnish 4.1 and Phoenix Cache, and I'm now totally lost. So any comment would be greatly appreciated, cheers!
