### ISSUE TITLE
Cannot redeclare Phoenix_VarnishCache_Adminhtml_VarnishCacheController::_isAllowed() in VarnishCacheController.php on line 155

### ISSUE THREAD

**Issue by schmite** [PHOENIX-MEDIA/Magento-PageCache-powered-by-Varnish#49]
This error is occurs when we click on Clean Varnish Cache. (varnishCache/clean):

"PHP message: PHP Fatal error:  Cannot redeclare Phoenix_VarnishCache_Adminhtml_VarnishCacheController::_isAllowed() in /htdocs/.modman/Magento-PageCache-powered-by-Varnish/app/code/community/Phoenix/VarnishCache/controllers/Adminhtml/VarnishCacheController.php on line 155" while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /index.php/admin/varnishCache/clean/key/7fe0841ea92203345929f2bbd2f512d4/

PageCache powered by Varnish Community version: 4.4.1
Magento version: 1.8.1.0
PHP version: 5.5.9

**Comment by deniscsz** [comment]
Fixed here: https://github.com/PHOENIX-MEDIA/Magento-PageCache-powered-by-Varnish/pull/50
