### ISSUE TITLE
Magento site couldn't be cached when user logged in

### ISSUE THREAD

**Issue by rakkiepianist** [PHOENIX-MEDIA/Magento-PageCache-powered-by-Varnish#52]
Hi, I have installed and configured PageCache to make Varnish work with Magento. 
When I am not logged in, I check the reponse header of the site and notice that Varnish works with Magento, and the site is cached by Varnish:
![1](https://cloud.githubusercontent.com/assets/13230680/15064672/2ce1c03c-1381-11e6-9322-4cb4cd0681de.jpg)

But when I log in with email and password, it seems that Varnish doesn't cache Magento site because there's a Set-Cookie header when logged in:
![2](https://cloud.githubusercontent.com/assets/13230680/15064738/fd1492e8-1381-11e6-8896-77b35fd8c557.jpg)

How can I resolve this problem to make Varnish work with Magento evenwhen logged in? Thank you so much!

**Comment by phoenix-bjoern** [comment]
Well, this is a feature of our PageCache powered by Varnish Enterprise module which is available as a subscription.

**Comment by rakkiepianist** [comment]
So with Enterprise edition, it couldn't be cached when a user logged in?

**Comment by phoenix-bjoern** [comment]
@linhvh _without_ Enterprise Edition of the PageCache module logged in users and users with shopping carts can not be cached, yes. The reason is that we've not implemented the necessary ESI in the free version.

**Comment by rakkiepianist** [comment]
Yeah, but now i need to fix this problem about user login as soon as possible. 
How can I implement these ESI policies to make it works, or where can I take the Enterprise version of the module?
Thank you so much!

**Comment by rakkiepianist** [comment]
@phoenix-bjoern Please i need to fix this problem as soon as possible, where can I take the Enterprise version of the module? May i have to install Magento EE?

**Comment by phoenix-bjoern** [comment]
There is not patch, it is an enhancement that comes in a separate module, the "Enterprise Edition".

You can subscribe here http://www.shareit.com/product.html?cart=1&productid=300449378&stylefrom=300449378

**Comment by rakkiepianist** [comment]
Thank you. Is there any other way to fix this logged-in user caching problem without using the enterprise module?

**Comment by phoenix-bjoern** [comment]
@linhvh This is not about a "fix" or a "bug", it is about a feature that has been implemented in the enterprise edition only.

I'm closing this ticket.
