### ISSUE TITLE
form_key

### ISSUE THREAD

**Issue by will-parsons** [PHOENIX-MEDIA/Magento-PageCache-powered-by-Varnish#6]
Unfortunately, the addition of form_key in Magento Community 1.8 will break 'add to cart' functionality when cached in Varnish.

Workarounds I've seen just seem to disable / bypass the form_keys entirely:

https://github.com/deivisonarthur/Inovarti_FixAddToCartMage18
https://bitbucket.org/supportdesk_nl/turpertine-formkey-workaround/src

Are there any plans to implement something similar?

Thanks!

**Comment by kneedrag1** [comment]
Still having the same issue, I think, as others reported.
Latest Git pull.  Magento 1.9.0.1

From varnishtop:
23.11 Debug          VCL_error(760, vPTgifwSf7IHFpmK)
23.11 VCL_return     error
23.11 Hash           /varnishcache/getformkey/
23.11 VCL_call       error
