### ISSUE TITLE
Varnish 4.0 support

### ISSUE THREAD

**Issue by Nemykal** [PHOENIX-MEDIA/Magento-PageCache-powered-by-Varnish#7]
Hi,
Varnish 4.0 was released recently and I'm interested in testing this module against it. From what I can tell it seems the VCL should be easy enough to adapt to the new syntax. 

Can you foresee any compatibility issues with this plugin and Varnish 4? Perhaps it might be worth including a default-4.0.vcl config file too.

**Comment by ankitce** [comment]
Tried with Varnish 4.0
Got below message while starting varnish.

Message from VCC-compiler:
Assert error in vcc_IdIs(), vcc_token.c line 283:
  Condition(t->tok == ID) not true.
  errno = 9 (Bad file descriptor)
Running VCC-compiler failed, signal 6, core dumped

VCL compilation failed

**Comment by sz00gun** [comment]
PHOENIX-MEDIA do you have a sample of vcl for Varnish 4? I would like to help and test it, if any bugs I will let you know, but I need this vcl file first ;)

Please advise

**Comment by proxium** [comment]
Any idea to fix vcl file with varnish 4

**Comment by deepblueair** [comment]
+1 we really need this, has been almost a year!

**Comment by MikeParkin** [comment]
@PHOENIX-MEDIA is 4.0 support still planned?

**Comment by PHOENIX-MEDIA** [comment]
Varnish 4 support has been added.
